const { test, expect } = require('playwright/test');
test.setTimeout(30000); if (process.env.RUNG_PLAYWRIGHT_CHROMIUM) test.use({ launchOptions: { executablePath: process.env.RUNG_PLAYWRIGHT_CHROMIUM } });
const ROOT=process.env.RUNG_BROWSER_ROOT||'http://127.0.0.1:5051', USER={email:'feature5-finish@example.com',password:'browser-finish'};
async function api(page, method, path, body) { return page.evaluate(async x => { const r=await fetch(x.path,{method:x.method,headers:x.body?{'Content-Type':'application/json'}:{},body:x.body?JSON.stringify(x.body):undefined}); return {status:r.status,data:await r.json().catch(()=>({}))}; },{method,path,body}); }
async function login(page) { await page.goto(ROOT); expect((await api(page,'POST','/api/auth/login',USER)).status).toBe(200); await page.reload(); const later=page.getByRole('button',{name:'Set up later'}); await later.waitFor({state:'visible',timeout:3000}).catch(()=>{}); if(await later.isVisible())await later.click(); }
test('Feature 5 Finished Shopping uses only persisted cart authority and completes once',async({page})=>{
 const errors=[],failed=[],requests=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())}); page.on('pageerror',e=>errors.push(e.message)); page.on('requestfailed',r=>failed.push(r.url())); page.on('response',r=>{const p=new URL(r.url()).pathname;if(['/api/grocery/finished-shopping/stage','/api/grocery/finished-shopping/complete'].includes(p))requests.push({method:r.request().method(),path:p,status:r.status()})});
 await page.setViewportSize({width:1440,height:1000}); await login(page); await page.locator('[data-target="shopping"]').click(); await expect(page.locator('.cart-current-title').first()).toHaveText('Finish detergent');
 const beforeCart=(await api(page,'GET','/api/shopping/current-cart')).data.cart, beforeMoney=(await api(page,'GET','/api/budget/summary')).data;
 expect(beforeCart).toMatchObject({status:'current',total:34}); expect(beforeCart.lines).toEqual([expect.objectContaining({product_id:'FIN-DETERGENT',package_count:2,unit_price:15,line_total:30}),expect.objectContaining({product_id:'FIN-SOAP',package_count:1,unit_price:4,line_total:4})]);
 const forged=await api(page,'POST','/api/grocery/finished-shopping/stage',{planned_total:.01,actual_total:999,retailer:'Fake',store_id:'fake',store_name:'Fake Store',cart_signature:'fake'}); expect(forged.status).toBe(200); expect(forged.data.trip_preview).toMatchObject({grocery_spending:34,planned_total:34,store_name:'Store B',store_id:'B',amount_source:'authoritative_cart'}); expect((await api(page,'GET','/api/shopping/current-cart')).data.cart).toEqual(beforeCart);
 await expect(page.locator('#finishedShoppingSummary')).toContainText('$34.00'); await page.screenshot({path:'/tmp/rung-feature5-finish-pre-desktop.png',fullPage:true});
 const staged=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/finished-shopping/stage'&&r.request().method()==='POST'); await page.locator('#completeShoppingTripBtn').click(); const stage=await staged; expect(stage.status()).toBe(200); await expect(page.locator('#finishedShoppingConfirmDialog')).toHaveAttribute('open',''); await expect(page.locator('#finishedShoppingConfirmBody')).toContainText('Store B'); await expect(page.locator('#finishedShoppingConfirmBody')).toContainText('$34.00'); await page.screenshot({path:'/tmp/rung-feature5-finish-confirm-desktop.png',fullPage:true}); await page.setViewportSize({width:390,height:844}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); await expect(page.locator('#finishedShoppingConfirmBtn')).toBeVisible(); await page.screenshot({path:'/tmp/rung-feature5-finish-confirm-mobile.png',fullPage:true}); await page.setViewportSize({width:1440,height:1000});
 const complete=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/finished-shopping/complete'&&r.request().method()==='POST'); await page.locator('#finishedShoppingConfirmBtn').click(); const completeResponse=await complete; expect(completeResponse.status()).toBe(200); const done=await completeResponse.json(); expect(done).toMatchObject({completed:true,already_completed:false,actual_total:34,planned_total:34,amount_source:'authoritative_cart'});
 const afterCart=(await api(page,'GET','/api/shopping/current-cart')).data.cart, afterMoney=(await api(page,'GET','/api/budget/summary')).data, txs=(await api(page,'GET','/api/transactions')).data; expect(afterCart).toBeNull(); expect(afterMoney.safe_to_spend.checking_cents).toBe(beforeMoney.safe_to_spend.checking_cents-3400); expect(txs.filter(t=>t.category==='grocery')).toHaveLength(1); const tx=txs.find(t=>t.category==='grocery'); expect(tx).toMatchObject({amount:34,can_delete:false}); await expect(page.locator('#finishedShoppingStatus')).toContainText('Shopping trip finished');
 await page.screenshot({path:'/tmp/rung-feature5-finish-success-desktop.png',fullPage:true}); await page.setViewportSize({width:390,height:844}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); await page.screenshot({path:'/tmp/rung-feature5-finish-success-mobile.png',fullPage:true}); await page.setViewportSize({width:1440,height:1000});
 const replay=await api(page,'POST','/api/grocery/finished-shopping/complete',{confirm:true,operation_id:done.operation_id,actual_total:999,store_id:'fake'}); expect(replay.status).toBe(200); expect(replay.data).toMatchObject({already_completed:true,actual_total:34}); expect((await api(page,'GET','/api/budget/summary')).data.safe_to_spend).toEqual(afterMoney.safe_to_spend);
 const historical=await api(page,'GET','/api/grocery/finished-shopping/status?operation_id='+done.operation_id); expect(historical.status).toBe(200); expect(historical.data).toMatchObject({completed:true,operation_id:done.operation_id,transaction_id:done.transaction_id,actual_total:34,store_id:'B',store_name:'Store B',retailer:'walmart',amount_source:'authoritative_cart'});
 // A later deliberate Build Cart establishes exactly one new current cart;
 // it cannot resurrect, relink, or economically reuse the completed trip.
 const laterBuild=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/generate-pay-period-plan'&&r.request().method()==='POST'); await page.locator('#buildCartBtn').click(); expect((await laterBuild).status()).toBe(200); const laterCart=(await api(page,'GET','/api/shopping/current-cart')).data.cart; expect(laterCart).toMatchObject({status:'current'}); expect(laterCart.id).not.toBe(beforeCart.id); expect(laterCart.lines).toHaveLength(1); expect(laterCart.lines[0]).toMatchObject({product_id:'LATER-DETERGENT',package_count:2,unit_price:11,line_total:22});
 const historicalAfter=await api(page,'GET','/api/grocery/finished-shopping/status?operation_id='+done.operation_id); expect(historicalAfter.status).toBe(200); expect(historicalAfter.data).toEqual(historical.data); const replayAfter=await api(page,'POST','/api/grocery/finished-shopping/complete',{confirm:true,operation_id:done.operation_id}); expect(replayAfter.status).toBe(200); expect(replayAfter.data.transaction_id).toBe(done.transaction_id); expect((await api(page,'GET','/api/transactions')).data.filter(t=>t.category==='grocery')).toHaveLength(1);
 const errorsBeforeProtectedDelete=errors.length; const denied=await api(page,'DELETE','/transactions/'+tx.id); expect(denied.status).toBe(409); await expect.poll(()=>errors.length).toBe(errorsBeforeProtectedDelete+1); expect(errors.at(-1)).toContain('409'); expect((await api(page,'GET','/api/transactions')).data.filter(t=>t.id===tx.id)).toHaveLength(1); expect((await api(page,'GET','/api/budget/summary')).data.safe_to_spend).toEqual(afterMoney.safe_to_spend);
 await page.reload(); await page.locator('[data-target="shopping"]').click(); await expect(page.locator('#finishedShoppingStatus')).toContainText('Finished: $34.00 at Store B'); expect(requests.filter(x=>x.path.endsWith('/complete'))).toHaveLength(3); expect(errors).toHaveLength(1); expect(failed).toEqual([]);
});
