const { test, expect } = require('playwright/test');
test.setTimeout(30000); if (process.env.RUNG_PLAYWRIGHT_CHROMIUM) test.use({ launchOptions: { executablePath: process.env.RUNG_PLAYWRIGHT_CHROMIUM } });
const ROOT = process.env.RUNG_BROWSER_ROOT || 'http://127.0.0.1:5051', USER = { email:'feature5-rebalance@example.com', password:'browser-rebalance' };
async function api(page, method, path, body) { return page.evaluate(async x => { const r=await fetch(x.path,{method:x.method,headers:x.body?{'Content-Type':'application/json'}:{},body:x.body?JSON.stringify(x.body):undefined}); return {status:r.status,data:await r.json().catch(()=>({}))}; }, {method,path,body}); }
async function login(page) { await page.goto(ROOT); expect((await api(page,'POST','/api/auth/login',USER)).status).toBe(200); await page.reload(); const later=page.getByRole('button',{name:'Set up later'}); await later.waitFor({state:'visible',timeout:3000}).catch(()=>{}); if(await later.isVisible()) await later.click(); }
test('Feature 5 Rebalance real UI stages, rejects, approves once, and reloads', async ({page}) => {
  const errors=[], failed=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())}); page.on('pageerror',e=>errors.push(e.message)); page.on('requestfailed',r=>failed.push(r.url()));
  await page.setViewportSize({width:1440,height:1000}); await login(page); await page.locator('[data-target="shopping"]').click();
  const before=(await api(page,'GET','/api/shopping/current-cart')).data.cart, money=(await api(page,'GET','/api/budget/summary')).data;
  expect(before.lines).toHaveLength(2); expect(before.lines[0]).toMatchObject({product_id:'RB-CURRENT',package_count:3,unit_price:10,line_total:30}); expect(before.lines[1]).toMatchObject({product_id:'RB-DISH',line_total:4});
  await page.locator('summary',{hasText:'Use a different budget for this trip'}).click(); await page.locator('#budgetInput').fill('20'); const preview=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/rebalance/preview'); await page.locator('#rebalanceCartBtn').click(); const previewResponse=await preview; expect(previewResponse.status()).toBe(200); expect(previewResponse.request().postDataJSON()).toMatchObject({budget_limit:20}); const first=(await previewResponse.json()).proposal;
  expect(first.status).toBe('pending'); expect(first.changes).toEqual([expect.objectContaining({old_product_id:'RB-CURRENT',proposed_product_id:'RB-VALUE',package_count:3,proposed_line_total:15})]); await expect(page.locator('#rebalanceReviewDialog')).toHaveAttribute('open',''); await expect(page.locator('#rebalanceReviewBody')).toContainText('Rebalance value detergent'); await page.screenshot({path:'/tmp/rung-feature5-rebalance-review-desktop.png',fullPage:true}); await page.setViewportSize({width:390,height:844}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); await page.screenshot({path:'/tmp/rung-feature5-rebalance-review-mobile.png',fullPage:true}); await page.setViewportSize({width:1440,height:1000});
  expect((await api(page,'GET','/api/shopping/current-cart')).data.cart).toEqual(before); expect((await api(page,'GET','/api/budget/summary')).data.safe_to_spend.safe_to_spend_cents).toBe(money.safe_to_spend.safe_to_spend_cents);
  const reject=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/rebalance/'+first.id+'/reject'); await page.locator('#rebalanceCancelBtn').click(); const rejected=await reject; expect(rejected.status()).toBe(200); expect((await rejected.json()).proposal.status).toBe('rejected'); expect((await api(page,'GET','/api/shopping/current-cart')).data.cart).toEqual(before);
  await page.reload(); await page.locator('[data-target="shopping"]').click(); await expect(page.locator('.cart-current-title').first()).toHaveText('Rebalance current detergent'); await page.locator('summary',{hasText:'Use a different budget for this trip'}).click(); await page.locator('#budgetInput').fill('20');
  const preview2=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/rebalance/preview'); await page.locator('#rebalanceCartBtn').click(); const second=(await (await preview2).json()).proposal; expect(second.id).not.toBe(first.id); expect(second.changes).toHaveLength(1);
  const apply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/grocery/rebalance/apply'); await page.locator('#rebalanceApplyBtn').click(); const applied=await apply; expect(applied.status()).toBe(200); expect((await applied.json()).proposal.status).toBe('approved');
  const after=(await api(page,'GET','/api/shopping/current-cart')).data.cart; expect(after).toMatchObject({id:before.id,version:before.version+1,total:19}); expect(after.lines[0]).toMatchObject({product_id:'RB-VALUE',package_count:3,unit_price:5,line_total:15}); expect(after.lines[1]).toMatchObject(before.lines[1]); expect((await api(page,'GET','/api/budget/summary')).data.safe_to_spend.safe_to_spend_cents).toBe(money.safe_to_spend.safe_to_spend_cents);
  const replay=await api(page,'POST','/api/grocery/rebalance/apply',{proposal_id:second.id}); expect(replay.status).toBe(200); expect(replay.data.proposal.status).toBe('approved'); expect((await api(page,'GET','/api/shopping/current-cart')).data.cart).toEqual(after); await page.reload(); await page.locator('[data-target="shopping"]').click(); await expect(page.locator('.cart-current-title').first()).toHaveText('Rebalance value detergent');
  await page.screenshot({path:'/tmp/rung-feature5-rebalance-desktop.png',fullPage:true}); await page.setViewportSize({width:390,height:844}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true); await page.screenshot({path:'/tmp/rung-feature5-rebalance-mobile.png',fullPage:true}); expect(errors).toEqual([]); expect(failed).toEqual([]);
});
