"""baseline schema

Revision ID: 76760617295f
Revises: 
Create Date: 2026-08-15 18:48:18.182952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76760617295f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('legacy_scope_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_scope_key'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('rapid_price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_keyword', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('package_size', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_per_serving', sa.Float(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('usage_frequency', sa.Integer(), nullable=True),
    sa.Column('last_selected_date', sa.DateTime(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('retail_product_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('store_address', sa.String(length=300), nullable=False),
    sa.Column('requested_query', sa.String(length=300), nullable=False),
    sa.Column('base_item', sa.String(length=150), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('us_item_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('package_size', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(length=30), nullable=True),
    sa.Column('provider_source', sa.String(length=80), nullable=False),
    sa.Column('verified_location', sa.Boolean(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer', 'store_id', 'requested_query', name='uq_retail_cache_store_query')
    )
    op.create_table('store_price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('item_keyword', sa.String(length=100), nullable=False),
    sa.Column('product_title', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('package_size', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('retailer', sa.String(length=50), nullable=True),
    sa.Column('is_store_brand', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('checking_balance', sa.Float(), nullable=True),
    sa.Column('food_allocation_pct', sa.Float(), nullable=True),
    sa.Column('pay_period_days', sa.Integer(), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('vault_balance', sa.Float(), nullable=True),
    sa.Column('expected_paycheck', sa.Float(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('city_state', sa.String(length=100), nullable=True),
    sa.Column('sales_tax_rate', sa.Float(), nullable=True),
    sa.Column('grocery_tax_rate', sa.Float(), nullable=True),
    sa.Column('balance_version', sa.Integer(), nullable=False),
    sa.Column('kroger_location_id', sa.String(length=20), nullable=True),
    sa.Column('kroger_store_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_household_id'), ['household_id'], unique=False)

    op.create_table('action_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('actions_json', sa.Text(), nullable=True),
    sa.Column('undo_token', sa.String(length=80), nullable=False),
    sa.Column('operation_id', sa.String(length=80), nullable=True),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'operation_id', name='uq_action_audit_household_operation_id'),
    sa.UniqueConstraint('household_id', 'undo_token', name='uq_action_audit_household_undo_token')
    )
    with op.batch_alter_table('action_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_audit_household_id'), ['household_id'], unique=False)

    op.create_table('beta_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('screen_context', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beta_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beta_feedback_household_id'), ['household_id'], unique=False)

    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_gas_estimate', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_household_id'), ['household_id'], unique=False)

    op.create_table('brand_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('clean_keyword', sa.String(length=100), nullable=False),
    sa.Column('prefer_store_brand', sa.Boolean(), nullable=True),
    sa.Column('preferred_brand_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'clean_keyword', name='uq_brand_pref_household_keyword')
    )
    with op.batch_alter_table('brand_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_preference_household_id'), ['household_id'], unique=False)

    op.create_table('grocery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('recipe_ids', sa.String(length=200), nullable=True),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('location_context', sa.String(length=100), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('shopping_requirement_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_items_household_id'), ['household_id'], unique=False)

    op.create_table('household_shopping_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('owner_scope', sa.String(length=120), nullable=False),
    sa.Column('preference_kind', sa.String(length=30), nullable=False),
    sa.Column('preference_key', sa.String(length=80), nullable=False),
    sa.Column('preference_value', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'preference_kind', 'preference_key', name='uq_household_default_scope_kind_key')
    )
    with op.batch_alter_table('household_shopping_defaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_shopping_defaults_household_id'), ['household_id'], unique=False)

    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'recipe_id', name='uq_meal_plan_household_recipe')
    )
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_household_id'), ['household_id'], unique=False)

    op.create_table('pantry_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('clean_keyword', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'clean_keyword', name='uq_pantry_household_keyword')
    )
    with op.batch_alter_table('pantry_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pantry_inventory_household_id'), ['household_id'], unique=False)

    op.create_table('plaid_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('owner_scope', sa.String(length=80), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=120), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.String(length=120), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('connection_status', sa.String(length=30), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_code', sa.String(length=120), nullable=True),
    sa.Column('last_error_message', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'plaid_item_id', name='uq_plaid_item_household_item'),
    sa.UniqueConstraint('plaid_item_id')
    )
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_item_household_id'), ['household_id'], unique=False)

    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('clean_keyword', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_product_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('base_item', sa.String(length=150), nullable=False),
    sa.Column('normalized_base_item', sa.String(length=150), nullable=False),
    sa.Column('preference_type', sa.String(length=20), nullable=False),
    sa.Column('preferred_brand', sa.String(length=150), nullable=True),
    sa.Column('preferred_variant', sa.String(length=150), nullable=True),
    sa.Column('preferred_package_size', sa.String(length=100), nullable=True),
    sa.Column('preferred_product_title', sa.String(length=300), nullable=False),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('retailer', sa.String(length=50), nullable=True),
    sa.Column('retailer_product_id', sa.String(length=100), nullable=True),
    sa.Column('retailer_us_item_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'normalized_base_item', 'preference_type', 'retailer', name='uq_retail_preference_base_type')
    )
    with op.batch_alter_table('retail_product_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retail_product_preference_household_id'), ['household_id'], unique=False)

    op.create_table('usage_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('owner_scope', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('external_call', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('cache_status', sa.String(length=20), nullable=True),
    sa.Column('force_refresh', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=80), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_micros', sa.Integer(), nullable=True),
    sa.Column('cost_status', sa.String(length=30), nullable=False),
    sa.Column('cost_rate_key', sa.String(length=120), nullable=True),
    sa.Column('operation_id', sa.String(length=120), nullable=True),
    sa.Column('request_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_event', schema=None) as batch_op:
        batch_op.create_index('ix_usage_event_category_provider_created', ['category', 'provider', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_event_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_usage_event_owner_created', ['owner_scope', 'created_at'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'key', name='uq_user_preference_household_key')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_household_id'), ['household_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'key', name='uq_user_setting_household_key')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_household_id'), ['household_id'], unique=False)

    op.create_table('expense_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('local_account_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['local_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id')
    )
    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_transactions_household_id'), ['household_id'], unique=False)

    op.create_table('plaid_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('owner_scope', sa.String(length=80), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=120), nullable=False),
    sa.Column('rung_account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('official_name', sa.String(length=200), nullable=True),
    sa.Column('mask', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=40), nullable=True),
    sa.Column('account_subtype', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_item.id'], ),
    sa.ForeignKeyConstraint(['rung_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'plaid_account_id', name='uq_plaid_account_household_account'),
    sa.UniqueConstraint('plaid_account_id')
    )
    with op.batch_alter_table('plaid_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_account_household_id'), ['household_id'], unique=False)

    op.create_table('plaid_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('owner_scope', sa.String(length=80), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=120), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=120), nullable=False),
    sa.Column('pending_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('replaces_pending_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('replaced_by_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('is_active_event', sa.Boolean(), nullable=False),
    sa.Column('pending_lifecycle_status', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('signed_amount_cents', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('merchant_name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('iso_currency_code', sa.String(length=10), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('authorized_date', sa.Date(), nullable=True),
    sa.Column('category_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_transaction_id')
    )
    with op.batch_alter_table('plaid_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_transaction_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_plaid_transaction_household_item_account', ['household_id', 'plaid_item_id', 'plaid_account_id'], unique=False)
        batch_op.create_index('ix_plaid_transaction_pending_id', ['pending_transaction_id'], unique=False)

    op.create_table('retail_product_substitution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('base_item', sa.String(length=150), nullable=False),
    sa.Column('normalized_base_item', sa.String(length=150), nullable=False),
    sa.Column('preferred_preference_id', sa.Integer(), nullable=False),
    sa.Column('substitute_brand', sa.String(length=150), nullable=True),
    sa.Column('substitute_variant', sa.String(length=150), nullable=True),
    sa.Column('substitute_package_size', sa.String(length=100), nullable=True),
    sa.Column('substitute_product_title', sa.String(length=300), nullable=False),
    sa.Column('substitute_upc', sa.String(length=50), nullable=True),
    sa.Column('retailer', sa.String(length=50), nullable=True),
    sa.Column('retailer_product_id', sa.String(length=100), nullable=True),
    sa.Column('retailer_us_item_id', sa.String(length=100), nullable=True),
    sa.Column('approval_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['preferred_preference_id'], ['retail_product_preference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'preferred_preference_id', 'retailer', 'retailer_us_item_id', name='uq_retail_substitution_preference_product')
    )
    with op.batch_alter_table('retail_product_substitution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retail_product_substitution_household_id'), ['household_id'], unique=False)

    op.create_table('shopping_trip_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=80), nullable=False),
    sa.Column('trip_token', sa.String(length=120), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(length=40), nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=False),
    sa.Column('store_id', sa.String(length=40), nullable=True),
    sa.Column('planned_total_cents', sa.Integer(), nullable=False),
    sa.Column('actual_total_cents', sa.Integer(), nullable=False),
    sa.Column('amount_source', sa.String(length=20), nullable=False),
    sa.Column('cart_signature', sa.String(length=120), nullable=False),
    sa.Column('manual_provisional', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['expense_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'operation_id', name='uq_shopping_trip_household_operation_id'),
    sa.UniqueConstraint('household_id', 'trip_token', name='uq_shopping_trip_household_trip_token')
    )
    with op.batch_alter_table('shopping_trip_completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_trip_completion_household_id'), ['household_id'], unique=False)

    op.create_table('transaction_reconciliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('owner_scope', sa.String(length=80), nullable=False),
    sa.Column('manual_transaction_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('match_strength', sa.Integer(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_action', sa.String(length=40), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['manual_transaction_id'], ['expense_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'manual_transaction_id', 'plaid_transaction_id', name='uq_tx_recon_owner_manual_plaid')
    )
    with op.batch_alter_table('transaction_reconciliation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_reconciliation_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_tx_recon_household_status', ['household_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_reconciliation', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_recon_household_status')
        batch_op.drop_index(batch_op.f('ix_transaction_reconciliation_household_id'))

    op.drop_table('transaction_reconciliation')
    with op.batch_alter_table('shopping_trip_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_trip_completion_household_id'))

    op.drop_table('shopping_trip_completion')
    with op.batch_alter_table('retail_product_substitution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retail_product_substitution_household_id'))

    op.drop_table('retail_product_substitution')
    with op.batch_alter_table('plaid_transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_plaid_transaction_pending_id')
        batch_op.drop_index('ix_plaid_transaction_household_item_account')
        batch_op.drop_index(batch_op.f('ix_plaid_transaction_household_id'))

    op.drop_table('plaid_transaction')
    with op.batch_alter_table('plaid_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_account_household_id'))

    op.drop_table('plaid_account')
    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_transactions_household_id'))

    op.drop_table('expense_transactions')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_household_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_household_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('usage_event', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_event_owner_created')
        batch_op.drop_index(batch_op.f('ix_usage_event_household_id'))
        batch_op.drop_index('ix_usage_event_category_provider_created')

    op.drop_table('usage_event')
    with op.batch_alter_table('retail_product_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retail_product_preference_household_id'))

    op.drop_table('retail_product_preference')
    op.drop_table('recipe_ingredient')
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_item_household_id'))

    op.drop_table('plaid_item')
    with op.batch_alter_table('pantry_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantry_inventory_household_id'))

    op.drop_table('pantry_inventory')
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_household_id'))

    op.drop_table('meal_plan')
    with op.batch_alter_table('household_shopping_defaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_shopping_defaults_household_id'))

    op.drop_table('household_shopping_defaults')
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_items_household_id'))

    op.drop_table('grocery_items')
    with op.batch_alter_table('brand_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_preference_household_id'))

    op.drop_table('brand_preference')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_household_id'))

    op.drop_table('bill')
    with op.batch_alter_table('beta_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beta_feedback_household_id'))

    op.drop_table('beta_feedback')
    with op.batch_alter_table('action_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_audit_household_id'))

    op.drop_table('action_audit')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_household_id'))

    op.drop_table('account')
    op.drop_table('store_price_cache')
    op.drop_table('retail_product_cache')
    op.drop_table('recipe')
    op.drop_table('rapid_price_cache')
    op.drop_table('household')
    # ### end Alembic commands ###
